[package]
name = "cli-wrapper"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
simplelog = { version = "^0.12.2", features = ["paris"] }

[profile.release]
opt-level = 3
strip = true
debug = true
